/**
 * Adapter layer types — platform-agnostic interfaces for all app operations.
 *
 * "FileRef" is an opaque reference to a file:
 *  - In Tauri mode  : a local filesystem path  (e.g. "/Users/foo/doc.xliff")
 *  - In Web mode    : a synthetic URI generated by the web adapter that
 *                     internally maps to a browser File object
 *                     (e.g. "web-file://550e8400-…")
 *
 * Components should treat FileRef as an opaque string and never parse it.
 */

import type {
  Project,
  Segment,
  TmEntry,
  TmMatch,
  TbEntry,
  TmSearchParams,
  TbLookupParams,
  QaIssue,
  MtTranslateParams,
  MtResult,
  MtSettings,
  ProjectStats,
  RecentProjects,
  LiveDocsLibrary,
  LiveDocsMatch,
} from "../types";

export type FileRef = string;

export interface OpenFileDialogOptions {
  multiple?: boolean;
  filters?: { name: string; extensions: string[] }[];
}

export interface SaveFileDialogOptions {
  defaultPath?: string;
  filters?: { name: string; extensions: string[] }[];
}

/**
 * Unified application adapter interface.
 * All platform-specific I/O goes through this interface.
 */
export interface IAppAdapter {
  // ── Dialog ────────────────────────────────────────────────────────────────
  /** Open a file picker. Returns a FileRef, or null if cancelled. */
  openFileDialog(options?: OpenFileDialogOptions): Promise<FileRef | null>;
  /**
   * Open a "save as" picker.
   * In Tauri: native save dialog → local path.
   * In Web  : returns the suggested filename; actual download is triggered
   *           by exportFile / saveProject.
   */
  saveFileDialog(options?: SaveFileDialogOptions): Promise<string | null>;

  // ── Project ───────────────────────────────────────────────────────────────
  parseFile(fileRef: FileRef): Promise<Project>;
  exportFile(segments: Segment[], sourcePath: string, outputPath: string): Promise<void>;
  saveProject(project: Project, savePath: string): Promise<void>;
  loadProject(fileRef: FileRef): Promise<Project>;
  addFileToProject(project: Project, fileRef: FileRef): Promise<Project>;
  removeFileFromProject(project: Project, fileId: string): Promise<Project>;
  getProjectStats(project: Project): Promise<ProjectStats>;
  getRecentProjects(): Promise<RecentProjects>;

  // ── Translation Memory ────────────────────────────────────────────────────
  createTm(name: string, sourceLang: string, targetLang: string): Promise<string>;
  addToTm(
    tmId: string,
    source: string,
    target: string,
    sourceLang: string,
    targetLang: string,
  ): Promise<TmEntry>;
  searchTm(params: TmSearchParams): Promise<TmMatch[]>;

  // ── Term Base ─────────────────────────────────────────────────────────────
  createTb(name: string): Promise<string>;
  lookupTb(params: TbLookupParams): Promise<TbEntry[]>;
  addToTb(
    tbId: string,
    sourceTerm: string,
    targetTerm: string,
    sourceLang: string,
    targetLang: string,
    notes: string,
    forbidden: boolean,
  ): Promise<TbEntry>;

  // ── Segment ───────────────────────────────────────────────────────────────
  saveSegment(
    projectId: string,
    segmentId: string,
    source: string,
    target: string,
    status: string,
    order: number,
  ): Promise<Segment>;

  // ── QA ───────────────────────────────────────────────────────────────────
  runQaCheck(projectId: string, tbId?: string): Promise<QaIssue[]>;

  // ── Machine Translation ───────────────────────────────────────────────────
  mtTranslate(params: MtTranslateParams): Promise<MtResult>;
  mtSaveSettings(settings: MtSettings): Promise<void>;
  mtLoadSettings(): Promise<MtSettings | null>;

  // ── LiveDocs ──────────────────────────────────────────────────────────────
  liveDocsCreateLibrary(name: string): Promise<LiveDocsLibrary>;
  liveDocsListLibraries(): Promise<LiveDocsLibrary[]>;
  liveDocsAddDocument(libId: string, fileRef: FileRef): Promise<LiveDocsLibrary>;
  liveDocsSearch(query: string, libId: string, minScore: number): Promise<LiveDocsMatch[]>;
}
